### ISSUE TITLE
use diskus library for file size calculation

### ISSUE THREAD

**Issue by amilajack** [amilajack/disk-utility#2]
Waiting on https://github.com/sharkdp/diskus/issues/12

**Comment by sharkdp** [comment]
It'S great to see that my code is being used in this project (`disk-utility/native/src/du.rs`), but please follow `diskus`'s licensing terms and add the respective copyright notices / licensing terms.

**Comment by amilajack** [comment]
So if i add a MIT license would that be fine?

**Comment by sharkdp** [comment]
MIT requires a copy of the license text and the original copyright notice ("2018, diskus developers").
Thanks.

**Comment by amilajack** [comment]
https://github.com/amilajack/disk-utility/blob/master/native/src/du.rs#L1. Done! Sorry for not including this in the first place. Didn't know this was a requirement of the MIT license. Will do this from now on.

**Comment by sharkdp** [comment]
No worries, thank you for the update!
